apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-frontend
  template:
    metadata:
      labels:
        app: nginx-frontend
    spec:
      containers:
        - name: frontend
          image: gcr.io/multi-cloud-platform/nginx-frontend:v1.x.x
          ports:
            - containerPort: 80
