apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: gcp-secrets
spec:
  provider: gcp
  parameters:
    secrets: |
      - resourceName: "projects/multi-cloud/secrets/app-secrets/versions/latest"
        path: "DATABASE_URI"
      - resourceName: "projects/multi-cloud/secrets/jwt-secret/versions/latest"
        path: "JWT_SECRET_KEY"
